# Data sources

The main source data we used is from the official website of FBI's UCR Programe which generates reliable crime statistics. We selected the 2019 hate crime statistics as our analysis object since this is the latest data available on website. The dataset collects details about offenders’ bias motivation associated with 13 offense types already being reported to the UCR Program: murder and nonnegligent manslaughter, rape, aggravated assault, simple assault, intimidation, human trafficking—commercial sex acts, and human trafficking—involuntary servitude (crimes against persons); and robbery, burglary, larceny-theft, motor vehicle theft, arson, and destruction/damage/vandalism (crimes against property) in each state. 

These are some socioeconomic factors we think that may have impacts on hate crimes. We abtain these variables from Kaiser Family Foundation's website. which is a nonprofit organization focusing on national health issues, as well as the U.S. role in global health policy. We use data on population demographics and wealth including breakdowns by race/ethnicity,  poverty by demographic groupings and unemployment rates.

The limitations of our data:
- Limited data for 2019 were available for Alabama.
- Some data in UCR's publication may not be comparable to those in prior editions of Hate Crime Statistics because of differing levels of participation from year to year.
- Most of the data is presented in the overall statistical data of each state, which may ignore some detailed features, and it also makes us seem to have very few observational data.

